[package]
name = "argus"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
schedulers = { path = "../schedulers" }
logs = { path = "../logs", optional = true }
errors = { path = "../errors", optional = true }

[features]
logs = ["dep:logs"]
errors = ["dep:errors"]
